language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: CcwPX3ujQOAOv0TmyOQyP01mfRzPY7rCBPct84T1SDiuNg+uaJpDif+W3ZHNK/8qv+tOjmqqNXrfi8/cQNolp+3DrdQSfp1qDyB0p/BYK455OUWyYVLINvvbGUu/jrbor1FVLCJ3mGc/MJ+5XpdR7GDGNuhVFZpUgF8bAyts6Z1e0m0wLzrfe0ah+gFO4z38C7Jywa3bmbzuKoa8gL1dmjDZMn/SkTGCyOy8/wdfuXzP2Hg7wxZOQ5i3xAX9YOQIAOpDn8xZRTPvAkSMkpo9xyrRqJYzESY2Jb+VoIh+himEc9hq0x4V6boIQGVePUdWp93gVsQgWjd7mZBo8Q6GPv2W1PS6qX3Ntdcopao2KxV2o3HPnvskBBQUVuGbqLORif/jI0MxitZgOabpW0CmF6hJR5byYow0MjvNeqKik5DxDTiGo1wZVDsS5EqrhJOYigjAu0IcHSJyb3+nO/yVtZMQB3iSKyB5Zlz98wTYIFmlaZ6dVyF7n7Dztmi6kOjqoLvG3IWNosVoEI/VCLIcVN0acUd4hmNhBG9lIe33pS66cODQ4MSjhLAYCbNbaF7Lxp3udt1AgaJCFnt+CYSFCelxlIiFI8jjx/gKV6nxkACu2ZIJpQCi69wZX0osOnesU7adiEauBLepNnWfCXGMN9xaVQRYTWgCahLbU6TWQXY=
  app: stormy-sea-31531
  on:
    repo: alysebos/node-shopping-list-integration-tests
